/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package NumeroDentroIntervalo;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
        
        
        int num = 0;
        
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Digite um valor: ");
        num = leitor.nextInt();
        
        if(num > 100 && num < 200){
            System.out.println("O valor informado esta entre 100 e 200.");
        }else{
            System.out.println("O valor informado NAO esta entre 100 e 200");
        }
        
        
        
        
    }
}
